const app = {
  closeWindow: 'Close',
  connecting: 'Connecting',
  connected: 'Connected',
  disconnected: 'Disconnected',
  connectingToMoke: 'Connecting to Moke',
  disconnectedFromMoke: 'Moke is disconnected',
  reconnecting: 'Reconnecting to Moke...',
  responseFailed: 'Could not send your response. Please try again.',
  sendFailed: 'Failed to send. Check that Moke is connected, then try again.',
  firstMessageSendFailed: 'Chat created, but the message was not sent. Your draft is ready to retry.',
  fileMenu: 'File',
  sessionCreateFailed: 'Could not create the chat. Check the workspace path and connection, then try again.',
  jumpToBottom: 'Jump to bottom',
  maximizeWindow: 'Maximize',
  minimizeWindow: 'Minimize',
  newChat: 'New chat',
  restoreWindow: 'Restore',
  settings: 'Settings',
  working: 'Working',
} as const

const browser = {
  addressPlaceholder: 'Search or enter URL',
  back: 'Back',
  clearDownloads: 'Clear downloads',
  closeOtherPages: 'Close other pages',
  closePage: 'Close page',
  closePagesToRight: 'Close pages to the right',
  errorTitle: 'Could not load this page',
  downloadCompleted: 'Downloaded',
  downloadFailed: 'Download failed',
  downloading: 'Downloading',
  downloads: 'Downloads',
  noDownloads: 'Downloaded files will appear here.',
  openDownloadedFile: 'Open file',
  revealDownloadedFile: 'Show in folder',
  forward: 'Forward',
  loading: 'Loading',
  maximize: 'Maximize browser',
  newPage: 'New page',
  openPromptDescription: 'Use the address bar to search the web or open a site.',
  openPromptTitle: 'Search or enter a URL',
  pages: 'Browser pages',
  reload: 'Reload',
  restore: 'Restore browser',
  retry: 'Try again',
  pageLimitReached: (count: number) => `Page limit reached (${count})`,
  requiresDesktopDescription: 'Pages are embedded in the right-side browser area.',
  requiresDesktopTitle: 'Use Moke in the Tauri desktop app',
} as const

const chat = {
  continuePrompt: 'Based on the result above, continue and turn it into a clearer next step.',
  emptyDescription: 'Give me a page, a question, or a direction.',
  emptyTitle: 'Where should we go first?',
  starters: [
    'Open ruanyifeng.com and summarize the latest post',
    'Read the current browser page and extract useful links',
    'Search the web for recent news about local LLM browsers',
  ],
  thinking: 'Moke is thinking',
  thinkingLabel: 'Thinking',
} as const

const composer = {
  add: 'Add',
  addImage: 'Add image',
  applyWorkspace: 'Apply',
  chooseImage: 'Choose image',
  chooseOtherWorkspace: 'Choose another folder',
  clearQueued: 'Clear queued messages',
  currentModel: (model: string, provider: string) => provider ? `${provider} · ${model}` : model,
  imageAttachment: 'Image attachment',
  imageReadFailed: 'Some images could not be read.',
  imageTooLarge: 'Images are limited to 4 MB each and 5 MB in total.',
  imageLimitReached: 'You can attach up to 4 images.',
  next: 'Next',
  nextUp: (count: number) => count > 1 ? `Next up · ${count}` : 'Next up',
  placeholder: 'Type a message',
  queuedAttachments: (count: number) => `Image × ${count}`,
  queuedMessages: 'Queued messages',
  recentWorkspaces: 'Recent',
  removeImage: 'Remove image',
  removeQueued: (index: number) => `Remove queued message ${index}`,
  removeQueuedTitle: (index: number) => `Remove message ${index}`,
  send: 'Send message',
  stoppingNext: 'Stopping · sends next automatically',
  stop: 'Stop running',
  stopAndSendNext: 'Stop current response and send next',
  workspace: 'Workspace',
  workspaceLabel: (root: string) => `Workspace: ${root || 'Not set'}`,
  thinking: 'Thinking',
  thinkingAuto: 'Auto',
  thinkingOption: (value: string) => {
    const labels: Record<string, string> = {
      off: 'Off',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      max: 'Max',
    }
    return labels[value] || value
  },
} as const

const header = {
  chooseWorkspaceApp: 'Choose application',
  collapseChatList: 'Collapse chat list',
  expandChatList: 'Expand chat list',
  hideBrowser: 'Hide browser',
  loadingWorkspaceApps: 'Loading applications',
  newChat: 'New chat',
  noWorkspace: 'Select a workspace first',
  noWorkspaceApps: 'No supported applications found',
  openWorkspaceIn: (name: string) => `Open workspace in ${name}`,
  showBrowser: 'Show browser',
  workspaceOpenFailed: 'Could not open the workspace',
} as const

const message = {
  copied: 'Copied',
  copyCode: 'Copy code',
  copyContent: 'Copy content',
  continue: 'Continue',
  forkChat: 'Fork chat',
} as const

const process = {
  active: (toolName: string) => `Running ${toolName}`,
  completedSteps: (count: number) => `Completed ${count} step${count === 1 ? '' : 's'}`,
  details: 'Process details',
  done: 'Done',
  emptyDirectory: 'Directory is empty',
  eventStatus: 'Status',
  exit: 'Exit',
  failed: 'Failed',
  issue: 'Issue',
  noResults: 'No matching results',
  notFound: 'No matching content found',
  output: 'Output',
  readEmpty: 'File is empty',
  reasoning: 'Reasoning',
  runIssue: 'Run note',
  runStatus: 'Process',
  shell: 'Shell',
  searchFailed: 'Search failed',
  success: 'Success',
  tool: 'Tool',
  toolFailed: (toolName: string, summary: string) => `Tool failed: ${toolName} · ${summary}`,
  unknownError: 'Unknown error',
  validationResult: 'Validation result',
  toolFailedFallback: 'Tool failed',
  working: 'Working',
  processed: 'Processed',
} as const

const settings = {
  active: 'Active',
  addProvider: 'Add provider',
  advanced: 'Advanced',
  apiBaseUrl: 'API Base URL',
  apiKey: 'API Key',
  browser: 'Browser',
  connection: 'Connection',
  currentTab: 'Current tab',
  defaultHome: 'Default home',
  delete: 'Delete',
  homeOpenMode: 'Link open mode',
  loadFailed: 'Failed to load model settings',
  loadModels: 'Load models',
  loading: 'Loading',
  model: 'Model',
  modelAvailable: 'Model is available',
  modelLoadFailed: 'Failed to load models',
  modelSaveFailed: 'Failed to save model settings',
  modelTestFailed: 'Model test failed',
  modelsLoaded: (count: number) => `Loaded ${count} model${count === 1 ? '' : 's'}`,
  name: 'Name',
  newTab: 'New tab',
  noModels: 'No models available',
  noPermissions: 'No authorized folders',
  openHome: 'Open home',
  permissions: 'Permissions',
  permissionsLoadFailed: 'Failed to load authorized folders',
  providerProfile: 'Provider profile',
  providerType: 'Type',
  refresh: 'Refresh',
  remove: 'Remove',
  removePermissionFailed: 'Failed to remove authorization',
  reasoning: 'Reasoning',
  reasoningHigh: 'High',
  reasoningHint: 'Controls llama.cpp thinking budget for compatible local servers.',
  reasoningLow: 'Low',
  reasoningMedium: 'Medium',
  reasoningOff: 'Off',
  reasoningProvider: 'Reasoning mode',
  reasoningProviderHint: 'Standard mode sends no provider-specific thinking parameters.',
  reasoningProviderLlamaCpp: 'llama.cpp thinking',
  reasoningProviderNone: 'Standard chat',
  responsesReasoningHint: 'Controls reasoning effort for OpenAI Responses models that support it.',
  reasoningMax: 'Max',
  retries: 'Retries',
  retriesHint: 'Retry failed model requests. Use 0 for fast local failures.',
  retriesPreview: (seconds: number, retries: number, reasoning: string) => `${seconds}s / ${retries} ${retries === 1 ? 'retry' : 'retries'} / ${reasoning}`,
  returnToChat: 'Back to chat',
  save: 'Save',
  saved: 'Saved',
  searchEngine: 'Search engine',
  searchEngineBaidu: 'Baidu',
  searchEngineBing: 'Bing',
  searchEngineGoogle: 'Google',
  setActive: 'Set active',
  testModel: 'Test model',
  testing: 'Testing',
  timeout: 'Timeout',
  timeoutHint: 'Seconds before a model request is stopped. Max 3600.',
  showRawReasoning: 'Show raw reasoning',
  showRawReasoningHint: 'Shows llama.cpp reasoning when the server returns it separately.',
  standardPreview: (seconds: number, retries: number) => `${seconds}s / ${retries} ${retries === 1 ? 'retry' : 'retries'}`,
} as const

const mcp = {
  disabled: 'disabled',
  enabled: 'enabled',
  invalidConfig: 'Invalid MCP config',
  noConfig: 'No MCP config file yet',
  noServers: 'No MCP servers configured.',
  reload: 'Reload',
  restartRequired: 'Saved config will take effect after server restart.',
  save: 'Save',
  savedRestart: 'Saved. Restart server to apply MCP changes.',
  saving: 'Saving',
  serverCount: (count: number) => `${count} server${count === 1 ? '' : 's'}`,
  simpleExample: 'Simple example',
  validate: 'Validate',
  validating: 'Validating',
  validConfig: 'MCP config is valid',
  loadFailed: 'Failed to load MCP config',
  saveFailed: 'Failed to save MCP config',
  validateFailed: 'Failed to validate MCP config',
} as const

const messaging = {
  add: 'Add',
  addDingTalk: 'Add DingTalk',
  addDingTalkFailed: 'Failed to add DingTalk channel',
  addFeishu: 'Add Feishu',
  addFeishuFailed: 'Failed to add Feishu channel',
  addWeChat: 'Add WeChat',
  allowedUsers: 'Allowed user IDs',
  allowedUsersPlaceholder: 'Optional, comma-separated',
  authorizationCancelled: 'Authorization cancelled',
  authorizationDenied: 'Authorization denied',
  authorizationFailed: 'Authorization failed',
  authorizationRequired: 'Authorization required',
  authorizationSucceeded: 'Authorization complete',
  availableChannels: 'Available channels',
  availableChannelsDescription: 'Choose a channel to add.',
  cancel: 'Cancel',
  channelCount: (count: number) => `${count} channel${count === 1 ? '' : 's'} configured`,
  checkAuthorizationFailed: 'Failed to check WeChat authorization',
  checkDingTalkAuthorizationFailed: 'Failed to check DingTalk authorization',
  checkFeishuAuthorizationFailed: 'Failed to check Feishu authorization',
  clientId: 'Client ID',
  clientSecret: 'Client Secret',
  cardTemplateId: 'Interactive card template ID',
  appId: 'App ID',
  appSecret: 'App Secret',
  close: 'Close',
  closeAuthorization: 'Close authorization',
  confirm: 'Confirm',
  confirmRemove: (platform: string) => `Remove the ${platform} channel?`,
  configureChannel: 'Configure channel',
  configureDingTalk: 'Configure DingTalk',
  connectDingTalkDescription: 'Create an internal app by QR code or enter app credentials.',
  connectFeishuDescription: 'Create a personal agent by QR code or enter app credentials.',
  connectWeChatDescription: 'Scan the QR code with WeChat to connect your account.',
  connected: 'Connected',
  connecting: 'Connecting',
  connectionError: 'Connection error',
  dingTalk: 'DingTalk',
  dingTalkQrCode: 'DingTalk authorization QR code',
  dingTalkDescription: 'Internal app / QR authorization',
  empty: 'Add a channel below to get started.',
  feishu: 'Feishu',
  feishuDescription: 'Personal agent / QR authorization',
  feishuQrCode: 'Feishu authorization QR code',
  feishuChina: 'Feishu (China)',
  invalidLoginResponse: 'Invalid authorization response',
  lastActive: (value: string) => `Last active ${value}`,
  loadFailed: 'Failed to load channels',
  loading: 'Loading channels',
  larkGlobal: 'Lark (Global)',
  manualSetup: 'Manual setup',
  noActivity: 'No recent activity',
  noChannels: 'No channels configured',
  optional: 'Optional',
  personalWeChat: 'Personal account · QR code authorization',
  preparingAuthorization: 'Preparing authorization',
  quickSetup: 'Quick setup',
  reauthorizeWeChat: 'Reauthorize WeChat',
  reconnecting: 'Reconnecting',
  region: 'Region',
  refreshChannels: 'Refresh channels',
  removeChannel: 'Remove channel',
  saveAndConnect: 'Save and connect',
  saveChanges: 'Save changes',
  scanWithWeChat: 'Scan with WeChat',
  scanWithDingTalk: 'Scan with DingTalk and confirm',
  scanWithFeishu: 'Scan with Feishu and confirm',
  scanWithLark: 'Scan with Lark and confirm',
  scannedConfirm: 'Confirm on your phone',
  startAuthorizationFailed: 'Failed to start WeChat authorization',
  startDingTalkAuthorizationFailed: 'Failed to start DingTalk authorization',
  startFeishuAuthorizationFailed: 'Failed to start Feishu authorization',
  startChannel: 'Start channel',
  stopped: 'Stopped',
  stopChannel: 'Stop channel',
  setupMethod: 'Setup method',
  tryAgain: 'Try again',
  updateFailed: 'Failed to update channel',
  verificationCode: 'Verification code',
  verificationFailed: 'Failed to verify the authorization code',
  verificationRequired: 'Enter verification code',
  weChat: 'WeChat',
  weChatQrCode: 'WeChat authorization QR code',
  yourChannels: 'Your channels',
  alreadyConnected: 'This account is already connected',
  qrExpired: 'QR code expired',
} as const

const skills = {
  add: 'Add skill',
  confirmDelete: (name: string) => `Delete "${name}"?`,
  countLabel: (count: number) => `${count} skill${count === 1 ? '' : 's'}`,
  deleteFailed: 'Failed to delete skill',
  deleted: 'Skill deleted',
  description: 'Description',
  disabled: 'Disabled',
  discardChanges: 'Discard unsaved skill changes?',
  empty: 'No skills configured',
  enabled: 'Enabled',
  id: 'ID',
  instructions: 'Instructions',
  invalid: 'Invalid',
  loadFailed: 'Failed to load skills',
  name: 'Name',
  newSkillName: 'New skill',
  saveFailed: 'Failed to save skill',
  saved: 'Skill saved',
  saving: 'Saving',
  statusFailed: 'Failed to update skill status',
  title: 'Skills',
  valid: 'Skill is valid',
  validate: 'Validate',
  validating: 'Validating',
  validationFailed: 'Failed to validate skill',
} as const

const sidebar = {
  chatActions: 'Chat actions',
  archive: 'Archive',
  chatName: 'Chat name',
  chats: 'Chats',
  clearSearch: 'Clear search',
  emptyDescription: 'Start a new chat from the sidebar.',
  emptyTitle: 'No chats yet',
  newChat: 'New chat',
  noResultsDescription: 'Try a different keyword.',
  noResultsTitle: 'No results',
  pin: 'Pin',
  rename: 'Rename',
  running: 'Running',
  scheduledSessionOrigin: 'Created by a scheduled task',
  scheduledTasks: 'Scheduled tasks',
  search: 'Search chats',
  settings: 'Settings',
  title: 'Moke',
  unpin: 'Unpin',
} as const

const tool = {
  applyPatchFallback: 'Apply code patch',
  browserPanel: 'Right panel',
  browserPage: 'Browser page',
  currentDialog: 'Current dialog',
  currentPage: 'Current page',
  currentViewport: 'Current viewport',
  currentWebPage: 'Current web page',
  fileContent: 'File content',
  keyboardAction: 'Keyboard action',
  listFiles: 'List files',
  localImage: 'Open local image',
  newTab: 'New tab',
  page: (pageId: string) => `Page ${pageId}`,
  pageOpened: 'Page opened',
  previousPage: 'Previous page',
  nextPage: 'Next page',
  pageForm: 'Page form',
  selectFile: 'Select file',
  targetElement: 'Target element',
  targetState: 'Target state',
  textContent: 'Text content',
  typeContent: 'Input content',
  unknownTool: 'Tool',
  changeLayout: 'Change layout',
  changePage: 'Change page',
  clickCompleted: 'Click completed',
  failedToReadDirectory: 'Failed to read directory',
  fullPage: 'Full page',
  input: 'Input',
  inputCompleted: 'Input completed',
  userInput: 'User input',
  approvalAllowedOnce: 'Allowed once',
  approvalAllowedSession: 'Allowed for chat',
  approvalAllowedAlways: 'Always allowed',
  approvalRejected: 'Rejected',
  rawDetails: 'Raw details',
  commandNoOutput: 'Command produced no output',
  pageStructureCaptured: 'Page structure captured',
  runCommand: 'Run command',
  runScript: 'Run script',
  runSearch: 'Run search',
  runTool: 'Run tool',
  screenshotCaptured: 'Screenshot captured',
  searchInProject: 'Search in project',
  skillConfig: 'Skill config',
  targetStateReached: 'Target state reached',
  viewDirectory: 'View directory',
  viewFile: 'View file',
  viewImage: 'View image',
  viewPage: 'View page',
  wait: 'Wait',
  waitingForResult: 'Waiting for result',
} as const

const approval = {
  allowExternalPath: 'Allow access to an external folder?',
  allowOnce: 'Allow once',
  allowSession: 'Allow for this chat',
  allowTool: 'Allow complex command?',
  commandWillRun: 'will run:',
  editContent: 'Edit content',
  externalPathReason: 'Reason: the requested path is outside the current workspace',
  permanent: 'Always allow',
  readFile: 'Read file',
  reject: 'Reject',
  requestAccess: 'requests access to:',
  runCommand: 'Run command',
  unknownTool: 'Action requiring approval',
  writeFile: 'Write file',
} as const

export const uiText = {
  app,
  approval,
  browser,
  chat,
  composer,
  header,
  message,
  messaging,
  mcp,
  process,
  settings,
  skills,
  sidebar,
  tool,
} as const
