const app = {
  connecting: 'Connecting',
  connected: 'Connected',
  disconnected: 'Disconnected',
  connectingToMoke: 'Connecting to Moke',
  disconnectedFromMoke: 'Moke is disconnected',
  connectionInterrupted: 'Connection to Moke was interrupted. This run has stopped.',
  sendFailed: 'Failed to send. Check that Moke is connected, then try again.',
  jumpToBottom: 'Jump to bottom',
  newChat: 'New chat',
  settings: 'Settings',
  settingsSubtitle: 'Models, permissions, and browser',
  waitingForApproval: 'Waiting for approval',
  waitingForResponse: 'Waiting for your response',
  waitingForResponseNote: 'Moke is waiting for your response',
  approvalRequiredNote: 'Approve the request to continue',
  working: 'Working',
} as const

const browser = {
  addressPlaceholder: 'Enter URL',
  back: 'Back',
  closePage: 'Close page',
  forward: 'Forward',
  loading: 'Loading',
  newPage: 'New page',
  openPromptDescription: 'The page will be embedded below with controls and status kept in the toolbar.',
  openPromptTitle: 'Enter a URL to visit',
  pages: 'Browser pages',
  reload: 'Reload',
  requiresDesktopDescription: 'Pages are embedded in the right-side browser area.',
  requiresDesktopTitle: 'Use Moke in the Tauri desktop app',
} as const

const chat = {
  continuePrompt: 'Based on the result above, continue and turn it into a clearer next step.',
  emptyDescription: 'Give me a page, a question, or a direction.',
  emptyTitle: 'Where should we go first?',
  starters: [
    'Open ruanyifeng.com and summarize the latest post',
    'Read the current browser page and extract useful links',
    'Search the web for recent news about local LLM browsers',
  ],
  thinking: 'Moke is thinking',
} as const

const composer = {
  add: 'Add',
  addImage: 'Add image',
  chooseImage: 'Choose image',
  clearQueued: 'Clear queued messages',
  imageAttachment: 'Image attachment',
  placeholder: 'Type a message',
  queued: (count: number) => `${count} queued`,
  queuedMessages: 'Queued messages',
  removeImage: 'Remove image',
  removeQueued: (index: number) => `Remove queued message ${index}`,
  removeQueuedTitle: (index: number) => `Remove message ${index}`,
  send: 'Send message',
  sendAfterStopping: 'Send after stopping',
  stop: 'Stop running',
  stopAndSendNext: 'Stop current response and send next',
  thinking: 'Thinking',
  thinkingAuto: 'Auto',
  thinkingOption: (value: string) => {
    const labels: Record<string, string> = {
      off: 'Off',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      ultra: 'Ultra',
    }
    return labels[value] || value
  },
} as const

const header = {
  collapseChatList: 'Collapse chat list',
  expandChatList: 'Expand chat list',
  hideBrowser: 'Hide browser',
  newChat: 'New chat',
  showBrowser: 'Show browser',
} as const

const message = {
  copied: 'Copied',
  copyCode: 'Copy code',
  copyContent: 'Copy content',
  continue: 'Continue',
  forkChat: 'Fork chat',
} as const

const process = {
  active: (toolName: string) => `Running ${toolName}`,
  completedSteps: (count: number) => `Completed ${count} step${count === 1 ? '' : 's'}`,
  details: 'Process details',
  done: 'Done',
  emptyDirectory: 'Directory is empty',
  eventStatus: 'Status',
  exit: 'Exit',
  failed: 'Failed',
  issue: 'Issue',
  noResults: 'No matching results',
  notFound: 'No matching content found',
  output: 'Output',
  readEmpty: 'File is empty',
  reasoning: 'Reasoning',
  runIssue: 'Run note',
  runStatus: 'Process',
  shell: 'Shell',
  searchFailed: 'Search failed',
  success: 'Success',
  tool: 'Tool',
  toolFailed: (toolName: string, summary: string) => `Tool failed: ${toolName} · ${summary}`,
  unknownError: 'Unknown error',
  validationResult: 'Validation result',
  toolFailedFallback: 'Tool failed',
  waitingApproval: (reason: string) => `Waiting for approval: ${reason}`,
} as const

const settings = {
  active: 'Active',
  addProvider: 'Add provider',
  advanced: 'Advanced',
  apiBaseUrl: 'API Base URL',
  apiKey: 'API Key',
  browser: 'Browser',
  currentTab: 'Current tab',
  defaultHome: 'Default home',
  delete: 'Delete',
  homeOpenMode: 'Link open mode',
  loadFailed: 'Failed to load model settings',
  loadModels: 'Load models',
  loading: 'Loading',
  model: 'Model',
  modelAvailable: 'Model is available',
  modelLoadFailed: 'Failed to load models',
  modelSaveFailed: 'Failed to save model settings',
  modelTestFailed: 'Model test failed',
  modelsLoaded: (count: number) => `Loaded ${count} model${count === 1 ? '' : 's'}`,
  name: 'Name',
  newTab: 'New tab',
  noModels: 'No models available',
  noPermissions: 'No authorized folders',
  openHome: 'Open home',
  permissions: 'Permissions',
  permissionsLoadFailed: 'Failed to load authorized folders',
  providerType: 'Type',
  refresh: 'Refresh',
  remove: 'Remove',
  removePermissionFailed: 'Failed to remove authorization',
  reasoning: 'Reasoning',
  reasoningHigh: 'High',
  reasoningHint: 'Controls llama.cpp thinking budget for compatible local servers.',
  reasoningLow: 'Low',
  reasoningMedium: 'Medium',
  reasoningOff: 'Off',
  reasoningProvider: 'Reasoning mode',
  reasoningProviderHint: 'Standard mode sends no provider-specific thinking parameters.',
  reasoningProviderLlamaCpp: 'llama.cpp thinking',
  reasoningProviderNone: 'Standard chat',
  reasoningUltra: 'Ultra',
  retries: 'Retries',
  retriesHint: 'Retry failed model requests. Use 0 for fast local failures.',
  retriesPreview: (seconds: number, retries: number, reasoning: string) => `${seconds}s / ${retries} ${retries === 1 ? 'retry' : 'retries'} / ${reasoning}`,
  returnToChat: 'Back to chat',
  save: 'Save',
  saved: 'Saved',
  setActive: 'Set active',
  testModel: 'Test model',
  testing: 'Testing',
  timeout: 'Timeout',
  timeoutHint: 'Seconds before a model request is stopped. Max 3600.',
  showRawReasoning: 'Show raw reasoning',
  showRawReasoningHint: 'Shows llama.cpp reasoning when the server returns it separately.',
  standardPreview: (seconds: number, retries: number) => `${seconds}s / ${retries} ${retries === 1 ? 'retry' : 'retries'}`,
} as const

const mcp = {
  disabled: 'disabled',
  enabled: 'enabled',
  invalidConfig: 'Invalid MCP config',
  noConfig: 'No MCP config file yet',
  noServers: 'No MCP servers configured.',
  reload: 'Reload',
  restartRequired: 'Saved config will take effect after server restart.',
  save: 'Save',
  savedRestart: 'Saved. Restart server to apply MCP changes.',
  saving: 'Saving',
  serverCount: (count: number) => `${count} server${count === 1 ? '' : 's'}`,
  simpleExample: 'Simple example',
  validate: 'Validate',
  validating: 'Validating',
  validConfig: 'MCP config is valid',
  loadFailed: 'Failed to load MCP config',
  saveFailed: 'Failed to save MCP config',
  validateFailed: 'Failed to validate MCP config',
} as const

const sidebar = {
  archive: 'Archive',
  chatName: 'Chat name',
  emptyDescription: 'Use the new chat button at the top to start.',
  emptyTitle: 'No chats yet',
  noResultsDescription: 'Try a different keyword.',
  noResultsTitle: 'No results',
  pin: 'Pin',
  rename: 'Rename',
  search: 'Search chats',
  settings: 'Settings',
  title: 'Chats',
  unpin: 'Unpin',
} as const

const tool = {
  applyPatchFallback: 'Apply code patch',
  browserPanel: 'Right panel',
  browserPage: 'Browser page',
  currentDialog: 'Current dialog',
  currentPage: 'Current page',
  currentViewport: 'Current viewport',
  currentWebPage: 'Current web page',
  fileContent: 'File content',
  keyboardAction: 'Keyboard action',
  listFiles: 'List files',
  localImage: 'Open local image',
  newTab: 'New tab',
  page: (pageId: string) => `Page ${pageId}`,
  pageOpened: 'Page opened',
  previousPage: 'Previous page',
  nextPage: 'Next page',
  pageForm: 'Page form',
  selectFile: 'Select file',
  targetElement: 'Target element',
  targetState: 'Target state',
  textContent: 'Text content',
  typeContent: 'Input content',
  unknownTool: 'Tool',
  availableSkills: 'Available skills',
  changeLayout: 'Change layout',
  changePage: 'Change page',
  clickCompleted: 'Click completed',
  failedToReadDirectory: 'Failed to read directory',
  fullPage: 'Full page',
  input: 'Input',
  inputCompleted: 'Input completed',
  json: 'JSON',
  commandNoOutput: 'Command produced no output',
  pageStructureCaptured: 'Page structure captured',
  runCommand: 'Run command',
  runScript: 'Run script',
  runSearch: 'Run search',
  runTool: 'Run tool',
  screenshotCaptured: 'Screenshot captured',
  searchInProject: 'Search in project',
  skillConfig: 'Skill config',
  targetStateReached: 'Target state reached',
  viewDirectory: 'View directory',
  viewFile: 'View file',
  viewImage: 'View image',
  viewPage: 'View page',
  viewTools: 'View tools',
  wait: 'Wait',
  waitingForResult: 'Waiting for result',
} as const

const toolLabel = {
  applyPatch: 'Edit content',
  bash: 'Run command',
  cat: 'Read file',
  execCommand: 'Run command',
  find: 'Search content',
  grep: 'Search content',
  ls: 'Browse files',
  npm: 'Run check',
  rg: 'Search content',
  sed: 'Read snippet',
  viewImage: 'View image',
} as const

const approval = {
  allowExternalPath: 'Allow access to an external folder?',
  allowOnce: 'Allow once',
  allowSession: 'Allow for this chat',
  allowTool: 'Allow complex command?',
  commandWillRun: 'will run:',
  editContent: 'Edit content',
  externalPathReason: 'Reason: the requested path is outside the current workspace',
  permanent: 'Always allow',
  readFile: 'Read file',
  reject: 'Reject',
  requestAccess: 'requests access to:',
  runCommand: 'Run command',
  unknownTool: 'Action requiring approval',
  writeFile: 'Write file',
} as const

export const uiText = {
  app,
  approval,
  browser,
  chat,
  composer,
  header,
  message,
  mcp,
  process,
  settings,
  sidebar,
  tool,
  toolLabel,
} as const
