const app = {
  closeWindow: 'Close',
  connecting: 'Connecting',
  connected: 'Connected',
  disconnected: 'Disconnected',
  connectingToMoke: 'Connecting to Moke',
  disconnectedFromMoke: 'Moke is disconnected',
  reconnecting: 'Reconnecting to Moke...',
  responseFailed: 'Could not send your response. Please try again.',
  sendFailed: 'Failed to send. Check that Moke is connected, then try again.',
  firstMessageSendFailed: 'Chat created, but the message was not sent. Your draft is ready to retry.',
  fileMenu: 'File',
  sessionCreateFailed: 'Could not create the chat. Check the workspace path and connection, then try again.',
  jumpToBottom: 'Jump to bottom',
  maximizeWindow: 'Maximize',
  minimizeWindow: 'Minimize',
  newChat: 'New chat',
  restoreWindow: 'Restore',
  settings: 'Settings',
  working: 'Working',
} as const

const browser = {
  addressPlaceholder: 'Search or enter URL',
  back: 'Back',
  clearDownloads: 'Clear downloads',
  closeOtherPages: 'Close other pages',
  closePage: 'Close page',
  closePagesToRight: 'Close pages to the right',
  errorTitle: 'Could not load this page',
  downloadCompleted: 'Downloaded',
  downloadFailed: 'Download failed',
  downloading: 'Downloading',
  downloads: 'Downloads',
  noDownloads: 'Downloaded files will appear here.',
  openDownloadedFile: 'Open file',
  revealDownloadedFile: 'Show in folder',
  forward: 'Forward',
  loading: 'Loading',
  maximize: 'Maximize browser',
  newPage: 'New page',
  openPromptDescription: 'Use the address bar to search the web or open a site.',
  openPromptTitle: 'Search or enter a URL',
  pages: 'Browser pages',
  reload: 'Reload',
  restore: 'Restore browser',
  retry: 'Try again',
  pageLimitReached: (count: number) => `Page limit reached (${count})`,
  requiresDesktopDescription: 'Pages are embedded in the right-side browser area.',
  requiresDesktopTitle: 'Use Moke in the Tauri desktop app',
} as const

const chat = {
  continuePrompt: 'Based on the result above, continue and turn it into a clearer next step.',
  emptyDescription: 'Ask a question, open a page, or work with your files.',
  emptyTitle: 'Where should we go first?',
  webStarters: [
    { title: 'Research a topic', prompt: 'Research this topic across reliable sources and summarize the key findings with links' },
    { title: 'Compare several sources', prompt: 'Compare these webpages and summarize the important differences and trade-offs' },
    { title: 'Check the latest updates', prompt: 'Check the latest official information about this topic and note what has changed' },
    { title: 'Summarize a webpage', prompt: 'Read this webpage and summarize its key points' },
    { title: 'Extract useful links', prompt: 'Read this webpage and extract its most useful links' },
    { title: 'Turn research into notes', prompt: 'Turn this research into concise notes with key facts and sources' },
  ],
  workspaceStarters: [
    { title: 'Summarize these files', prompt: 'Summarize the key points, decisions, and action items in these files' },
    { title: 'Draft a report', prompt: 'Draft a clear report from the relevant files in this folder' },
    { title: 'Compare these documents', prompt: 'Compare the relevant documents and highlight important differences' },
    { title: 'Extract key information', prompt: 'Extract the important names, dates, amounts, and other structured information' },
    { title: 'Create action items', prompt: 'Turn these documents into action items with owners and deadlines when available' },
    { title: 'Organize this folder', prompt: 'Review this folder and suggest a clear organization and filing plan' },
  ],
  thinking: 'Moke is thinking',
  thinkingLabel: 'Thinking',
} as const

const composer = {
  add: 'Add',
  addFilesOrImages: 'Add files or images',
  addImage: 'Add image',
  applyWorkspace: 'Apply',
  chooseProject: 'Choose project',
  chooseOtherWorkspace: 'Choose another folder',
  clearQueued: 'Clear queued messages',
  currentModel: (model: string, provider: string) => provider ? `${provider} · ${model}` : model,
  fileAttachment: 'File attachment',
  imageAttachment: 'Image attachment',
  imageReadFailed: 'Some images could not be read.',
  imageTooLarge: 'Images are limited to 4 MB each and 5 MB in total.',
  imageLimitReached: 'You can attach up to 4 images.',
  next: 'Next',
  nextUp: (count: number) => count > 1 ? `Next up · ${count}` : 'Next up',
  placeholder: 'Type a message',
  queuedAttachments: (count: number) => `Image × ${count}`,
  queuedMessages: 'Queued messages',
  recentWorkspaces: 'Recent',
  removeImage: 'Remove image',
  removeFile: (name: string) => `Remove ${name}`,
  removeQueued: (index: number) => `Remove queued message ${index}`,
  removeQueuedTitle: (index: number) => `Remove message ${index}`,
  send: 'Send message',
  stoppingNext: 'Stopping · sends next automatically',
  stop: 'Stop running',
  stopAndSendNext: 'Stop current response and send next',
  workspace: 'Workspace',
  workspaceLabel: (root: string) => `Workspace: ${root || 'Not set'}`,
  thinking: 'Thinking',
  thinkingAuto: 'Auto',
  thinkingOption: (value: string) => {
    const labels: Record<string, string> = {
      off: 'Off',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      max: 'Max',
    }
    return labels[value] || value
  },
} as const

const header = {
  chooseWorkspaceApp: 'Choose application',
  collapseChatList: 'Collapse chat list',
  expandChatList: 'Expand chat list',
  hideBrowser: 'Hide browser',
  loadingWorkspaceApps: 'Loading applications',
  newChat: 'New chat',
  noWorkspace: 'Select a workspace first',
  noWorkspaceApps: 'No supported applications found',
  openWorkspaceIn: (name: string) => `Open workspace in ${name}`,
  showBrowser: 'Show browser',
  workspaceOpenFailed: 'Could not open the workspace',
} as const

const message = {
  copied: 'Copied',
  copyCode: 'Copy code',
  copyContent: 'Copy content',
  continue: 'Continue',
  forkChat: 'Fork chat',
} as const

const process = {
  active: (toolName: string) => `Running ${toolName}`,
  completedSteps: (count: number) => `Completed ${count} step${count === 1 ? '' : 's'}`,
  details: 'Process details',
  done: 'Done',
  emptyDirectory: 'Directory is empty',
  eventStatus: 'Status',
  exit: 'Exit',
  failed: 'Failed',
  issue: 'Issue',
  noResults: 'No matching results',
  notFound: 'No matching content found',
  output: 'Output',
  readEmpty: 'File is empty',
  reasoning: 'Reasoning',
  runIssue: 'Run note',
  runStatus: 'Process',
  shell: 'Shell',
  searchFailed: 'Search failed',
  success: 'Success',
  tool: 'Tool',
  toolFailed: (toolName: string, summary: string) => `Tool failed: ${toolName} · ${summary}`,
  unknownError: 'Unknown error',
  validationResult: 'Validation result',
  toolFailedFallback: 'Tool failed',
  working: 'Working',
  processed: 'Processed',
} as const

const settings = {
  addProvider: 'Add provider',
  apiBaseUrl: 'API Base URL',
  apiKey: 'API Key',
  connectionStatus: 'Connection status',
  authorizedFolders: 'Authorized folders',
  authorizedFoldersDescription: 'Folders approved for agent file access.',
  browser: 'Browser',
  connection: 'Connection',
  browserCache: 'Cache',
  browserCookies: 'Cookies and site data',
  browserData: 'Browsing data',
  browserSearch: 'Search',
  cacheCleared: 'Cache cleared',
  clearBrowserDataFailed: 'Failed to clear browser data',
  clearCache: 'Clear cache',
  clearCacheDescription: 'Clear HTTP cache, Cache Storage, and Service Workers. Cookies and local site data are kept.',
  clearCookies: 'Clear cookies and site data',
  clearCookiesDescription: 'Cookies, local site data, and cache. This action cannot be undone.',
  clearing: 'Clearing...',
  confirmClearCookies: 'This removes cookies, local site data, cached files, and Service Workers from the built-in browser. You will be signed out of websites. This action cannot be undone.',
  confirmClearCookiesAction: 'Clear website data',
  confirmClearCookiesTitle: 'Clear cookies and website data?',
  confirmDeleteProvider: (name: string) => `Delete "${name}"? This provider configuration will be removed. This action cannot be undone.`,
  confirmDeleteProviderAction: 'Delete provider',
  confirmDeleteProviderTitle: 'Delete model provider?',
  confirmDiscardModelChanges: 'Your unsaved provider changes will be lost.',
  confirmDiscardModelChangesAction: 'Discard changes',
  confirmDiscardChangesTitle: 'Discard unsaved changes?',
  confirmRevokePermission: (path: string) => `Moke and future agent runs will no longer be able to access "${path}" unless you authorize it again.`,
  confirmRevokePermissionAction: 'Remove authorization',
  confirmRevokePermissionTitle: 'Remove folder authorization?',
  cancel: 'Cancel',
  desktopOnly: 'Available in the desktop app',
  defaultProvider: 'Default',
  delete: 'Delete',
  loadFailed: 'Failed to load model settings',
  loadModels: 'Load models',
  loading: 'Loading',
  model: 'Model',
  modelAvailable: 'Model is available',
  modelLoadFailed: 'Failed to load models',
  modelSaveFailed: 'Failed to save model settings',
  modelTestFailed: 'Model test failed',
  makeDefault: 'Make Default',
  modelsLoaded: (count: number) => `Loaded ${count} model${count === 1 ? '' : 's'}`,
  name: 'Name',
  noModels: 'No models available',
  notTested: 'Not tested',
  noPermissions: 'No folders have been authorized.',
  cookiesCleared: 'Cookies, site data, and cache cleared',
  permissions: 'Permissions',
  permissionAdded: (date: string) => `Authorized ${date}`,
  permissionAuthorized: 'Authorized',
  permissionsLoadFailed: 'Failed to load authorized folders',
  providerProfile: 'Provider profile',
  providers: 'Providers',
  providerCount: (count: number) => `${count} provider${count === 1 ? '' : 's'}`,
  providerType: 'Type',
  refresh: 'Refresh',
  remove: 'Remove',
  removePermissionLabel: (path: string) => `Remove authorization for ${path}`,
  removePermissionFailed: 'Failed to remove authorization',
  reasoning: 'Reasoning',
  reasoningHigh: 'High',
  reasoningHint: 'Controls llama.cpp thinking budget for compatible local servers.',
  reasoningLow: 'Low',
  reasoningMedium: 'Medium',
  reasoningOff: 'Off',
  reasoningProvider: 'Reasoning mode',
  reasoningProviderHint: 'Standard mode sends no provider-specific thinking parameters.',
  reasoningProviderLlamaCpp: 'llama.cpp thinking',
  reasoningProviderNone: 'Standard chat',
  responsesReasoningHint: 'Controls reasoning effort for OpenAI Responses models that support it.',
  reasoningMax: 'Max',
  retries: 'Retries',
  retriesHint: 'Retry failed model requests. Use 0 for fast local failures.',
  retriesPreview: (seconds: number, retries: number, reasoning: string) => `${seconds}s / ${retries} ${retries === 1 ? 'retry' : 'retries'} / ${reasoning}`,
  returnToChat: 'Back to chat',
  requestBehavior: 'Request behavior',
  revert: 'Revert',
  save: 'Save',
  saveBeforeActivating: 'Save changes before setting this provider active',
  searchEngine: 'Search engine',
  searchEngineBaidu: 'Baidu',
  searchEngineBing: 'Bing',
  searchEngineGoogle: 'Google',
  testConnection: 'Test Connection',
  testing: 'Testing',
  timeout: 'Timeout',
  timeoutHint: 'Seconds before a model request is stopped. Max 3600.',
  unsaved: 'Unsaved',
  showRawReasoning: 'Show raw reasoning',
  showApiKey: 'Show API key',
  hideApiKey: 'Hide API key',
  showRawReasoningHint: 'Shows llama.cpp reasoning when the server returns it separately.',
  standardPreview: (seconds: number, retries: number) => `${seconds}s / ${retries} ${retries === 1 ? 'retry' : 'retries'}`,
} as const

const mcp = {
  add: 'Add',
  addServer: 'Add MCP service',
  allow: 'Allow',
  arguments: 'Arguments',
  argumentsHint: 'Enter one argument per line.',
  argumentsPlaceholder: 'path/to/workspace',
  cancel: 'Cancel',
  close: 'Close',
  command: 'Start command',
  commandPlaceholder: 'npx @example/mcp-server',
  confirmRemove: (name: string) => `Remove “${name}”? Moke will no longer be able to use this service.`,
  configFile: 'Configuration file',
  configuration: 'Configuration',
  configurationJson: 'Configuration JSON',
  edit: 'Edit',
  editLabel: (name: string) => `Edit ${name}`,
  editServer: 'Edit MCP service',
  editorDescription: 'Enter the information provided by the MCP service.',
  enable: 'Enable',
  invalidConfig: 'Invalid MCP config',
  localTool: 'Local MCP service',
  name: 'Name',
  nameHint: 'Use letters, numbers, hyphens, or underscores.',
  needsApproval: 'Needs approval',
  noConfig: 'No MCP config file yet',
  noServers: 'No MCP servers configured.',
  pause: 'Pause',
  paused: 'Paused',
  ready: 'Ready',
  reload: 'Reload',
  remove: 'Remove',
  removeFailed: 'Failed to remove MCP service',
  removed: 'MCP service removed',
  removeLabel: (name: string) => `Remove ${name}`,
  removeServer: 'Remove MCP service?',
  restartRequired: 'Saved. Restart Moke to apply this service change.',
  save: 'Save',
  saveServer: 'Save service',
  savedRestart: 'Saved. Restart Moke to apply this service change.',
  saving: 'Saving',
  serverCount: (count: number) => `${count} server${count === 1 ? '' : 's'}`,
  servers: 'Servers',
  serversDescription: 'Add a local MCP service to give Moke more tools.',
  trustGranted: 'MCP service allowed',
  trustFailed: 'Failed to update MCP service permission',
  toggleLabel: (name: string) => `Enable or pause ${name}`,
  loadFailed: 'Failed to load MCP config',
  saveFailed: 'Failed to save MCP config',
} as const

const messaging = {
  add: 'Add',
  addChannel: 'Add channel',
  addDingTalk: 'Add DingTalk',
  addDingTalkFailed: 'Failed to add DingTalk channel',
  addFeishu: 'Add Feishu',
  addFeishuFailed: 'Failed to add Feishu channel',
  addWeChat: 'Add WeChat',
  allowedUsers: 'Allowed user IDs',
  allowedUsersPlaceholder: 'Optional, comma-separated',
  authorizationCancelled: 'Authorization cancelled',
  authorizationDenied: 'Authorization denied',
  authorizationFailed: 'Authorization failed',
  authorizationRequired: 'Authorization required',
  authorizationSucceeded: 'Authorization complete',
  availableChannels: 'Available channels',
  availableChannelsDescription: 'Choose a channel to add.',
  cancel: 'Cancel',
  channelCount: (count: number) => `${count} channel${count === 1 ? '' : 's'} configured`,
  checkAuthorizationFailed: 'Failed to check WeChat authorization',
  checkDingTalkAuthorizationFailed: 'Failed to check DingTalk authorization',
  checkFeishuAuthorizationFailed: 'Failed to check Feishu authorization',
  clientId: 'Client ID',
  clientSecret: 'Client Secret',
  cardTemplateId: 'Interactive card template ID',
  appId: 'App ID',
  appSecret: 'App Secret',
  close: 'Close',
  closeAuthorization: 'Close authorization',
  confirm: 'Confirm',
  confirmRemove: (platform: string) => `Remove the ${platform} channel?`,
  configureChannel: 'Configure channel',
  configureDingTalk: 'Configure DingTalk',
  connectDingTalkDescription: 'Create an internal app by QR code or enter app credentials.',
  connectFeishuDescription: 'Create a personal agent by QR code or enter app credentials.',
  connectWeChatDescription: 'Scan the QR code with WeChat to connect your account.',
  connected: 'Connected',
  connecting: 'Connecting',
  connectionError: 'Connection error',
  dingTalk: 'DingTalk',
  dingTalkQrCode: 'DingTalk authorization QR code',
  dingTalkDescription: 'Internal app / QR authorization',
  empty: 'Add a channel below to get started.',
  feishu: 'Feishu',
  feishuDescription: 'Personal agent / QR authorization',
  feishuQrCode: 'Feishu authorization QR code',
  feishuChina: 'Feishu (China)',
  invalidLoginResponse: 'Invalid authorization response',
  lastActive: (value: string) => `Last active ${value}`,
  loadFailed: 'Failed to load channels',
  loading: 'Loading channels',
  larkGlobal: 'Lark (Global)',
  manualSetup: 'Manual setup',
  noActivity: 'No recent activity',
  noChannels: 'No channels configured',
  optional: 'Optional',
  personalWeChat: 'Personal account · QR code authorization',
  preparingAuthorization: 'Preparing authorization',
  quickSetup: 'Quick setup',
  reauthorizeWeChat: 'Reauthorize WeChat',
  reconnecting: 'Reconnecting',
  region: 'Region',
  refreshChannels: 'Refresh channels',
  removeChannel: 'Remove channel',
  saveAndConnect: 'Save and connect',
  saveChanges: 'Save changes',
  scanWithWeChat: 'Scan with WeChat',
  scanWithDingTalk: 'Scan with DingTalk and confirm',
  scanWithFeishu: 'Scan with Feishu and confirm',
  scanWithLark: 'Scan with Lark and confirm',
  scannedConfirm: 'Confirm on your phone',
  startAuthorizationFailed: 'Failed to start WeChat authorization',
  startDingTalkAuthorizationFailed: 'Failed to start DingTalk authorization',
  startFeishuAuthorizationFailed: 'Failed to start Feishu authorization',
  startChannel: 'Start channel',
  stopped: 'Stopped',
  stopChannel: 'Stop channel',
  setupMethod: 'Setup method',
  tryAgain: 'Try again',
  updateFailed: 'Failed to update channel',
  verificationCode: 'Verification code',
  verificationFailed: 'Failed to verify the authorization code',
  verificationRequired: 'Enter verification code',
  weChat: 'WeChat',
  weChatQrCode: 'WeChat authorization QR code',
  yourChannels: 'Your channels',
  alreadyConnected: 'This account is already connected',
  qrExpired: 'QR code expired',
} as const

const skills = {
  all: 'All',
  confirmDelete: (name: string) => `Delete "${name}"?`,
  countLabel: (count: number) => `${count} skill${count === 1 ? '' : 's'}`,
  deleteLabel: (name: string) => `Delete ${name}`,
  deleteTitle: 'Delete skill?',
  deleteFailed: 'Failed to delete skill',
  deleted: 'Skill deleted',
  disabled: 'Disabled',
  empty: 'No skills configured',
  enabled: 'Enabled',
  filterLabel: 'Skill status',
  import: 'Import skill',
  imported: 'Skill imported. Enable it when you are ready to use it.',
  importing: 'Importing...',
  importFailed: 'Failed to import skill',
  invalid: 'Invalid',
  loadFailed: 'Failed to load skills',
  statusFailed: 'Failed to update skill status',
  title: 'Skills',
} as const

const sidebar = {
  chatActions: 'Chat actions',
  archive: 'Archive',
  chatName: 'Chat name',
  chats: 'Chats',
  clearSearch: 'Clear search',
  emptyDescription: 'Start a new chat from the sidebar.',
  emptyTitle: 'No chats yet',
  newChat: 'New chat',
  noResultsDescription: 'Try a different keyword.',
  noResultsTitle: 'No results',
  pin: 'Pin',
  rename: 'Rename',
  running: 'Running',
  scheduledSessionOrigin: 'Created by a scheduled task',
  scheduledTasks: 'Scheduled tasks',
  search: 'Search chats',
  settings: 'Settings',
  title: 'Moke',
  unpin: 'Unpin',
} as const

const tool = {
  applyPatchFallback: 'Apply code patch',
  browserPanel: 'Right panel',
  browserPage: 'Browser page',
  currentDialog: 'Current dialog',
  currentPage: 'Current page',
  currentViewport: 'Current viewport',
  currentWebPage: 'Current web page',
  fileContent: 'File content',
  keyboardAction: 'Keyboard action',
  listFiles: 'List files',
  localImage: 'Open local image',
  newTab: 'New tab',
  page: (pageId: string) => `Page ${pageId}`,
  pageOpened: 'Page opened',
  previousPage: 'Previous page',
  nextPage: 'Next page',
  pageForm: 'Page form',
  selectFile: 'Select file',
  targetElement: 'Target element',
  targetState: 'Target state',
  textContent: 'Text content',
  typeContent: 'Input content',
  unknownTool: 'Tool',
  changeLayout: 'Change layout',
  changePage: 'Change page',
  clickCompleted: 'Click completed',
  failedToReadDirectory: 'Failed to read directory',
  fullPage: 'Full page',
  input: 'Input',
  inputCompleted: 'Input completed',
  userInput: 'User input',
  approvalAllowedOnce: 'Allowed once',
  approvalAllowedSession: 'Allowed for chat',
  approvalAllowedAlways: 'Always allowed',
  approvalRejected: 'Rejected',
  rawDetails: 'Raw details',
  commandNoOutput: 'Command produced no output',
  pageStructureCaptured: 'Page structure captured',
  runCommand: 'Run command',
  runScript: 'Run script',
  runSearch: 'Run search',
  runTool: 'Run tool',
  screenshotCaptured: 'Screenshot captured',
  searchInProject: 'Search in project',
  skillConfig: 'Skill config',
  targetStateReached: 'Target state reached',
  viewDirectory: 'View directory',
  viewFile: 'View file',
  viewImage: 'View image',
  viewPage: 'View page',
  wait: 'Wait',
  waitingForResult: 'Waiting for result',
} as const

const approval = {
  allowExternalPath: 'Allow access to an external folder?',
  allowMessage: 'Allow sending this message?',
  allowOnce: 'Allow once',
  allowSession: 'Allow for this chat',
  allowTool: 'Allow complex command?',
  commandWillRun: 'will run:',
  messageContent: 'Content:',
  messageWillSend: 'will send to:',
  mcpTool: 'MCP tool',
  editContent: 'Edit content',
  externalPathReason: 'Reason: the requested path is outside the current workspace',
  permanent: 'Always allow',
  readFile: 'Read file',
  reject: 'Reject',
  requestAccess: 'requests access to:',
  runCommand: 'Run command',
  sendMessage: 'Send message',
  unknownTool: 'Action requiring approval',
  writeFile: 'Write file',
} as const

export const uiText = {
  app,
  approval,
  browser,
  chat,
  composer,
  header,
  message,
  messaging,
  mcp,
  process,
  settings,
  skills,
  sidebar,
  tool,
} as const
