import type { RunManager, RuntimeRun, ToolRegistry } from '@moke/agent-runtime';
import type { BrowserBridge } from '../services/browser-bridge.js';
import type { McpSettingsService } from '../services/mcp-settings-service.js';
import type { PermissionsService } from '../services/permissions-service.js';
import type { SettingsService } from '../services/settings-service.js';
import type { SkillSettingsService } from '../services/skill-settings-service.js';
import type { SessionRepository } from '../storage/session-store.js';
import type { AttachmentStore } from '../storage/attachment-store.js';
import type { MessagingRuntime } from '../services/messaging/messaging-runtime.js';
import type { WeixinLoginService } from '../services/messaging/weixin-login-service.js';
import type { FeishuLoginService } from '../services/messaging/feishu-login-service.js';
import type { DingTalkLoginService } from '../services/messaging/dingtalk-login-service.js';
import type { ScheduledTaskService } from '../services/scheduled-task-service.js';
import type { DiscoveryService } from '../services/discovery-service.js';

export type RoutesContext = {
  sessionStore: SessionRepository;
  attachmentStore: AttachmentStore;
  runs: Map<string, RuntimeRun>;
  runManager: RunManager;
  toolRegistry: ToolRegistry;
  browserBridge: BrowserBridge;
  mcpSettingsService: McpSettingsService;
  permissionsService: PermissionsService;
  settingsService: SettingsService;
  skillSettingsService: SkillSettingsService;
  messagingRuntime: MessagingRuntime;
  weixinLoginService: WeixinLoginService;
  feishuLoginService: FeishuLoginService;
  dingtalkLoginService: DingTalkLoginService;
  scheduledTaskService: ScheduledTaskService;
  defaultWorkspaceRoot: string;
  discoveryService: DiscoveryService;
};
